src/basics.jl, src/examples/files.jl, src/routing.jl
update: changed `Void` to (`@compat Void`) to avoid @shashi's concern about v0.3
=> Fix deprecation warnings on 0.4

src/routing.jl
Pretty trivial change. I think this is the only deprecation that needs to be fixed here in Mux (the core is really very small!). Tests work when Hiccup is checked out, but latest tagged Hiccup is pretty broken on nightly. So let's hope that Mux's Hiccup dependency is not tested here (it seems to only be used in one file).
=> symbol ⇒ Symbol

README.md, src/Mux.jl, src/examples/files.jl
A file at `MyPkg/assets/js/test.js` will be served at `/pkg/MyPkg/js/test.js`
supersedes https://github.com/JunoLab/Blink.jl/pull/55
=> Serve package asset files

.travis.yml, REQUIRE, src/Mux.jl, src/examples/files.jl
Introduce a common package which holds a key -> path dictionary of files to serve by default in Mux.
Packages interested in serving static files can register with this base package without depending on Mux.
=> AssetRegistry

src/Mux.jl
See log http://juliarun-ci.s3.amazonaws.com/ca683dcf21cca54bea956d5705f03fb45796d6ea/pull_request_of_WebIO_on_julia_0_6.log for METADATA PR https://github.com/JuliaLang/METADATA.jl/pull/15399.
> INFO: Building WebIO
WARNING: Module Mux with uuid 6556077278318599 is missing from the cache.
This may mean module Mux does not support precompilation but is imported by a module that does.
ERROR: LoadError: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
=> enable precompilation

README.md
It was mucking up rendering in GitHub.
=> Change non-breaking spaces to spaces in README headings

.travis.yml, REQUIRE, appveyor.yml, src/websockets_integration.jl
This is necessary to get WebIO.jl working again on 0.7
=> turn websockets integration back on

src/basics.jl
Sometimes the error messages are too long.
I think `break word` will let user read the message more easily.
Screen shot:
=> break words for error message page

README.md, src/Mux.jl, src/basics.jl, test/runtests.jl
While `Mux.defaults` is great for development and debugging purposes, it
should definitely not be used in a Production application, due to the
inclusion of the `basiccatch` middleware, which dumps stacktraces to
clients. Reword the README to indicate that one should instead roll
their own stack.
=> Recommend against using defaults in Production

Project.toml
There is a [CompatHelper upgrade to Lazy](https://github.com/JuliaWeb/Mux.jl/commit/7cbc92cea995849656396511d174c322f67bab08) that needs to make it out to release. 
Fix #110
=> Make a minor release

src/routing.jl, test/runtests.jl
Maybe these are no big deal, but I think if passing 1 or 3 functions to `page` calls `page([], app...)`, 2 functions should also call that.
I think another decent option would be to deprecate `page(func, path)`.
Also applies to `route`.
=> Fix stack overflows with page(func, func)

Project.toml, README.md, src/routing.jl
It's a typo. I don't know if this is worth doing or not, though!
=> Rename "probabilty" -> "probability"

test/runtests.jl
Changes:
ce32c3b (Colin Caine, 79 seconds ago)
Test websocket server
1b32062 (Colin Caine, 63 seconds ago)
Reorganise tests
Putting them in testsets makes it a bit easier to see what's going on if 
one of them fails, in my opinion.
=> Test WebSockets and reorganise tests

src/basics.jl
This avoids two hash lookups and one call to HTTP.URIs.URI
=> Use req[:uri] directly in splitquery

src/routing.jl
=> Use Base.Callable instead of Function in signatures

Project.toml, README.md, src/server.jl, test/runtests.jl
Have a `serve` method that accepts an additional port to listen for websockets. Allows serving both general http requests and websocket requests using a single call to `serve`.
fixes: #146
=> fix serve api that integrates websockets

src/examples/files.jl
Currently assetserving fails when files contain spaces or other url-forbidden characters.
I propose to modify `assetserve()` in order to solve that issue.
=> support assetserving of files with spaces

src/Mux.jl, src/backtrace_rewriting.jl, src/basics.jl, test/runtests.jl
Replaces #140.
I rewrote this because I wanted us to correctly match the braces, which isn't practical with Regex.
I'll merge this in a few days if there are no objections or suggestions.
=> Print `::Mux.Closure` instead of `::Mux.var""{...}`

src/Mux.jl
I was reading through the code a bit and IMO it would be beneficial to define `defaults`, `wdefaults`, and `prod_defaults` as constants. In that way the compiler has more guarantees which should be helpful when they are used in other functions or downstream code.
=> Define `defaults`, `wdefaults` and `prod_defaults` as `const`

README.md
I wasn't able to get this to run robustly, this seems to work better. Previously I was getting `send is not defined`, which presumably means that Mux is not exporting `send` from `HTTP.WebSockets`.
=> update websocket example in README
